### ISSUE TITLE
Unique user_data per instance

### ISSUE THREAD

**Issue by iAdmin-PL** [terraform-aws-modules/terraform-aws-ec2-instance#108]
Is there any way to put user_data unique per instance ?
I would like to push cloud_init with hostnames set according to names registered in R53.

So for example node-1.test.com I would have hostname set accordingly.

# EC2
module "ec2_instances" {
  associate_public_ip_address = "false"
  source                  = "terraform-aws-modules/ec2-instance/aws"
  version                 = "~> 2.0"
  name                    = "${var.name}"
  instance_count          = "${var.instance_count}"
  ami                     = "${data.aws_ami.ami.id}"
  instance_type           = "${var.instance_type}"
  key_name                = "${var.ec2_key_name}"
  monitoring              = "false"
  private_ips             = tolist(var.static_ip_list)
  vpc_security_group_ids  = ["${module.security_group.security_group_id}"]
  subnet_ids              = tolist(data.aws_subnet_ids.subnets_tag.ids)
  user_data               = "$data.template_file.cloud_init_template_file.rendered"

Terraform 0.12.3

**Comment by antonbabenko** [comment]
@iAdmin-PL No, this is not supported and won't be supported in the nearest future. You need to call this module with the different user_data every time you need to have a difference.
