### ISSUE TITLE
There is no option for user_data in base64 format.

### ISSUE THREAD

**Issue by erlonpinheiro** [terraform-aws-modules/terraform-aws-ec2-instance#117]
The module just support user_data parameter which can support just 64 KB. If we have a user_data_base64 option we could have bigger data in there.

**Comment by antonbabenko** [comment]
[v2.11.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v2.11.0) of this module has been released with this feature supported.
