### ISSUE TITLE
Using this module but elb not being able to read output of id

### ISSUE THREAD

**Issue by ranvijayj** [terraform-aws-modules/terraform-aws-ec2-instance#12]
```
 instances                   = [ "${module.frontend_api.id}" ]
  cross_zone_load_balancing   = true
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400
}

module "frontend_api" 
{
  source = "terraform-aws-modules/ec2-instance/aws"
  name = "${var.environment}-app"
  count = 1
  ami                   = "ami-7f675e4f"
  instance_type          = "t2.micro"
  key_name               = "terraform_acc"
  monitoring             = true
  subnet_id              = "${aws_subnet.tf_test_subnet.id}"
  vpc_security_group_ids = ["${aws_security_group.default.id}"]
  disk_size         = 50 

#iam_instance_profile = 
  
  tags = {
    Terraform = "true"
    Environment = "dev"
  }
}
```

Everything else got launched. Even EC2 came up. But when I try to use instances inside elb and give it a value it gives the below:

![screen shot 2018-01-16 at 8 18 17 pm](https://user-images.githubusercontent.com/10911504/34994727-722f6038-fafa-11e7-9751-7c53c9fd1991.png)

Can you please help? or is this a bug?

**Comment by FernandoMiguel** [comment]
what's in the module "terraform-aws-modules/ec2-instance/aws"?
also why double quotes?

-- 
Fernando Miguel
https://FernandoMiguel.net

**Comment by ranvijayj** [comment]
Sorry that was typo for the double quotes.

https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/1.1.0
This is there ^^

**Comment by FernandoMiguel** [comment]
there's no LB resource there.
where are you creating the LB?

**Comment by ranvijayj** [comment]
Will this help?
https://gist.github.com/ranvijayj/9c294ac4de47d4c27b5483f47f998ecf

I pasted the modules in the above 1.10 link in another folder and tried again if Ic omment out the 
instances = part of elb resource everything works

**Comment by FernandoMiguel** [comment]
you should probably be using a launch configuration instead of ec2 resources.
and use a ALB

that way instances will register directly

**Comment by ranvijayj** [comment]
But I will just have 1 private server under the elb. 
This should work right? id variable should be a valid output of list of instance ids.

**Comment by ranvijayj** [comment]
@antonbabenko

**Comment by ranvijayj** [comment]
Worked now. outputs.tf for the ec2 module had a different variable name and i was calling another one while list elb `instances`

**Comment by antonbabenko** [comment]
Normally you can run `examples` in all [terraform-aws-modules](https://github.com/terraform-aws-modules) which show most common use-cases.

I was about to run [this example](https://github.com/terraform-aws-modules/terraform-aws-elb/tree/master/examples/complete) to verify that it still works as expected. Glad that you found the solution faster!
