### ISSUE TITLE
output of ARN -- any reason why this isn't added?

### ISSUE THREAD

**Issue by gyoza** [terraform-aws-modules/terraform-aws-ec2-instance#127]
just wondering if there is a technical reason? Its very easy to add... wondering if you guys could add this? 

Its a default export of the aws_instance provider. Thanks!

**Comment by antonbabenko** [comment]
Thank you for opening this issue!

This is now available in [v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v2.10.0) of this module.
