### ISSUE TITLE
network_interface var unused still?

### ISSUE THREAD

**Issue by Dogers** [terraform-aws-modules/terraform-aws-ec2-instance#132]
I see the comment that "network_interface can't be specified together with associate_public_ip_address" but is this still the case with TF 0.12? Can one or the other not be conditionally nulled out now?

Just throwing this out there for discussion as I've not done much in 0.12 as yet, so not sure how flexible it is now.

**Comment by antonbabenko** [comment]
Good catch! :)

This is now available in [v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v2.10.0) of this module.
