### ISSUE TITLE
Add lifecycle support

### ISSUE THREAD

**Issue by IlyaKochnev** [terraform-aws-modules/terraform-aws-ec2-instance#141]
That would be nice to have [lifecycle ] (https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations)
support in this module.
It's very useful to maintain the instance and ignore changes in case of user_data or ami have been changed.

**Comment by meabed** [comment]
yes please this is very much need in a lot of use cases
for example: when launching with dynamic AMI image, if the image changed it force re-creation
or any other attribute changes. 
It would be great to enable this through another variable array of ignore changes passed down to the module.
Thank you!

**Comment by ryanwohara** [comment]
@antonbabenko Is this a PR that you would accept? I'm happy to tweak it if you need anything changed.

**Comment by antonbabenko** [comment]
Closing this issue, see #144 for an explanation.
