### ISSUE TITLE
root_block_device - Not Accepting Variable Input

### ISSUE THREAD

**Issue by stephenh1991** [terraform-aws-modules/terraform-aws-ec2-instance#16]
**TF version**

0.11.2 & 0.11.3

**problem**

```HCL
module "ec2" {

[... ]

root_block_device = {

  volume_type                = "gp2"
  volume_size                 = "16"
  delete_on_termination = "true"

}

[... ]

}
```

**Terraform apply result: **

```
Terraform v0.11.3

Configuring remote state backend...
Initializing Terraform configuration...

Error: module.aws_instance.aws_instance.aws_instance: root_block_device: should be a list
```

I have managed to fix the problem by adding to my own fork of the module: 

```HCL
root_block_device      = ["${var.root_block_device}"]
```

I think this might actually be a bug in Terraform itself but wanted to see if this was an edge case I've introduced. Can anyone else confirm seeing this?

Cheers,
Steve

**Comment by antonbabenko** [comment]
Try this: ```hcl
module "ec2" {

[... ]

root_block_device = [{

  volume_type                = "gp2"
  volume_size                 = "16"
  delete_on_termination = "true"

}]

[... ]

}
```

**Comment by stephenh1991** [comment]
Hi Anton,

Thanks for this, I tested it and yes it works. I think it's a bit obscure for the user given that the value of the variable block is:

```HCL
variable "root_block_device" {
  description = "Customize details about the root block device of the instance. See Block Devices below for details"
  default     = {}
}
```

Either the description should change or in the module main block add:

```HCL
root_block_device      = ["${var.root_block_device}"]
```

Cheers,
Steve

**Comment by antonbabenko** [comment]
I don't remember right now why, but this won't work equally well when you want to provide one or none value. This was the main reason why this is done the way it is done.
