### ISSUE TITLE
Support for lifecycle

### ISSUE THREAD

**Issue by nerdingasnate** [terraform-aws-modules/terraform-aws-ec2-instance#161]
Hi,

I would like to be able to specify if i want something to be ignored.

ie. it would be useful for me not to recreate all the instances when new ami is specified, but just create new ones with it:

lifecycle {
    ignore_changes = ["ami"]
  }

Thanks

**Comment by antonbabenko** [comment]
This is a rather repetitive issue in this repository.

Many users want this functionality, but it isn't possible to use variables in the `lifecycle` block in Terraform so we can't do much in this module.

Closing this issue.
