### ISSUE TITLE
Instance-id 

### ISSUE THREAD

**Issue by sharathmankala** [terraform-aws-modules/terraform-aws-ec2-instance#169]
Hi Team,
I am wring terraform script for  AWS ALB, so i want to know how to get instance-id using tags.
Please some one help me.

**Comment by antonbabenko** [comment]
Hi @sharathmankala !

Please ask general Terraform questions on https://discuss.hashicorp.com/ or stackoverflow.

Here is an ALB module you can use - https://github.com/terraform-aws-modules/terraform-aws-alb/

Here is a data-source which you can use to find EC2 instances by tags - https://www.terraform.io/docs/providers/aws/d/instances.html

Closing this issue.
