### ISSUE TITLE
Question: Is it possible to add provisioner config to this module?

### ISSUE THREAD

**Issue by certain-ops** [terraform-aws-modules/terraform-aws-ec2-instance#17]
It'd be cool to subclass this module and add my own provisioner and connection variables. Is that possible?

**Comment by antonbabenko** [comment]
Adding provisioners is hard because there can be different types of provisioners and this code will be very complicated and yet incomplete, so I don't think it will be the way to go for this generic resource module.

**Comment by danihodovic** [comment]
@antonbabenko so if we need provisioning of an instance we can't use this module at all?

**Comment by antonbabenko** [comment]
@danihodovic You are right. Fork it and add provisioners or other custom functionality you need.
