### ISSUE TITLE
Error downloading modules: Error loading modules: module ec2_linux: Error parsing .terraform/modules/7d673a754841031e07eaafd4f93209e0/data.tf: At 2:14: Unknown token: 2:14 IDENT aws.local 

### ISSUE THREAD

**Issue by neethumoltp** [terraform-aws-modules/terraform-aws-ec2-instance#177]
Im getting "Unknown token " error while creating ec2 instance.

**Comment by bryantbiggs** [comment]
hi @neethumoltp - sorry but without any information we can't help further troubleshoot. please feel free to open a new issue with more information if necessary
