### ISSUE TITLE
Unable to download!

### ISSUE THREAD

**Issue by DebashishDebnath** [terraform-aws-modules/terraform-aws-ec2-instance#179]
I was trying to use this module but unable to download it. I was trying from Cygwin and Windows cmd as well but no luck.

Am I missing something?

CODE:

module "ec2_cluster" {
  source  = **"terraform-aws-modules/ec2-instance/aws"**
  version = "~> 2.0"

  name           = "my-cluster"
  instance_count = 1

  ami           = "ami-0c94855ba95c71c99"
  instance_type = "t2.micro"
  subnet_id     = "subnet-eddcdzz4"

  tags = {
    Terraform   = "true"
    Environment = "dev"
  }
}

-----------

$ terraform init
2020/09/26 03:14:54 [INFO] Terraform version: 0.13.3
2020/09/26 03:14:54 [INFO] Go runtime version: go1.14.7
2020/09/26 03:14:54 [INFO] CLI args: []string{"C:\\cygwin64\\bin\\terraform.exe", "init"}
2020/09/26 03:14:54 [DEBUG] Attempting to open CLI config file: C:\Users\XXXXX\AppData\Roaming\terraform.rc
2020/09/26 03:14:54 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/09/26 03:14:54 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/09/26 03:14:54 [DEBUG] ignoring non-existing provider search directory C:\Users\XXXXX\AppData\Roaming\terraform.d\plugins
2020/09/26 03:14:54 [DEBUG] ignoring non-existing provider search directory C:\Users\XXXXX\AppData\Roaming\HashiCorp\Terraform\plugins
2020/09/26 03:14:54 [INFO] CLI command args: []string{"init"}
2020/09/26 03:14:54 [TRACE] ModuleInstaller: installing child modules for . into .terraform\modules
Initial2020/09/26 03:14:54 [DEBUG] Module installer: begin ec2_cluster
iz2020/09/26 03:14:54 [TRACE] ModuleInstaller: ec2_cluster is not yet installed
2020/09/26 03:14:54 [TRACE] ModuleInstaller: cleaning directory .terraform\modules\ec2_cluster prior to install of ec2_cluster
in2020/09/26 03:14:54 [TRACE] ModuleInstaller: ec2_cluster is a registry module at terraform-aws-modules/ec2-instance/aws
2020/09/26 03:14:54 [DEBUG] ec2_cluster listing available versions of terraform-aws-modules/ec2-instance/aws at registry.terraform.io
2020/09/26 03:14:54 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
g module2020/09/26 03:14:54 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
s...
2020/09/26 03:14:54 [DEBUG] fetching module versions from "https://registry.terraform.io/v1/modules/terraform-aws-modules/ec2-instance/aws/versions"
2020/09/26 03:14:54 [DEBUG] GET https://registry.terraform.io/v1/modules/terraform-aws-modules/ec2-instance/aws/versions
2020/09/26 03:14:54 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-aws-modules/ec2-instance/aws/versions
2020/09/26 03:14:54 [DEBUG] found available version "2.15.0" for terraform-aws-modules/ec2-instance/aws
2020/09/26 03:14:54 [DEBUG] found available version "2.12.0" for terraform-aws-modules/ec2-instance/aws
2020/09/26 03:14:54 [DEBUG] found available version "1.21.0" for terraform-aws-modules/ec2-instance/aws

2020/09/26 03:14:54 [DEBUG] found available version "1.2.0" for terraform-aws-modules/ec2-instance/aws
2020/09/26 03:14:54 [DEBUG] looking up module location from "https://registry.terraform.io/v1/modules/terraform-aws-modules/ec2-instance/aws/2.15.0/download"
2020/09/26 03:14:54 [DEBUG] GET https://registry.terraform.io/v1/modules/terraform-aws-modules/ec2-instance/aws/2.15.0/download
2020/09nloading terr/26 03:14:54 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-aws-modules/ec2-instance/aws/2.15.0/download
aform-aws-modules/ec2-instance/aws 2.15.0 for ec2_cluster...
2020/09/26 03:14:54 [TRACE] ModuleInstaller: ec2_cluster terraform-aws-modules/ec2-instance/aws 2.15.0 is available at "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.15.0"
2020/09/26 03:14:54 [DEBUG] will download "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.15.0" to .terraform\modules\ec2_cluster
2020/09/26 03:14:54 [TRACE] fetching "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.15.0" to ".terraform\\modules\\ec2_cluster"
2020/09/26 03:14:54 [TRACE] modsdir: writing modules manifest to .terraform\modules\modules.json

Error: Failed to download module

Could not download module "ec2_cluster" (registry-module.tf:37) source code
from
"git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.15.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.15.0':
git must be available and on the PATH.

**Comment by DebashishDebnath** [comment]
Seems it is working now. Could not able to find out what's the main reason. If someone can put a light that will be great!

**Comment by antonbabenko** [comment]
Usually, such issues are related to the behavior of services involved - Terraform Registry and GitHub.

There is nothing that we can do in the module.

**Comment by DebashishDebnath** [comment]
Thanks for the update.
