### ISSUE TITLE
does not work with root_block_device type list

### ISSUE THREAD

**Issue by pkchuyen** [terraform-aws-modules/terraform-aws-ec2-instance#18]
I have an issue with create custom size for root block device for EC2 instance

> root_block_device      = "${var.root_block_device}"

while root_block_device should be type map

>   root_block_device {
>     volume_type           = "gp2"
>     volume_size           = 100
>     delete_on_termination = true
>   }

maybe i am wrong because we might have another way to do it with current module code which i could not figure out.

I am happy with pushing a PR for fixing it.

main.tf
> root_block_device {
>     volume_type           = "${var.root_block_device.type}"
>     volume_size           = "${var.root_block_device.size}"
>     delete_on_termination = "${var.root_block_device.delete_on_termination}"
>   }

**Comment by pkchuyen** [comment]
my terraform version
tf --version
Terraform v0.10.6

**Comment by antonbabenko** [comment]
`root_block_device` is a list, so you should be able to pass values like this:
```hcl
module "ec2" {

  root_block_device = [{
volume_type = "gp2"
volume_size = 100
delete_on_termination = true
}]

# the rest is omitted...
}
```

If this does not work, please submit a PR which fixes it.

**Comment by pkchuyen** [comment]
it works like charm with your guidance.
Could be great if we can put it in the example 

Thanks for the quick support

**Comment by eddideku** [comment]
@antonbabenko THANKS FOR THIS!
