### ISSUE TITLE
Question about the required subnet_id when launch instance.

### ISSUE THREAD

**Issue by JamesYuan** [terraform-aws-modules/terraform-aws-ec2-instance#180]
Hi,

I know the wiki have noted these:

One of subnet_id or subnet_ids is required. If both are provided, the value of subnet_id is prepended to the value of subnet_ids.

But I am still curious why it is necessary when launch 1 instance. Even use the origin simple "aws_instance" resource, the subnet_id is not necessary parameter.

resource "aws_instance" "srv" {
  ami           = var.aws_ami
  instance_type = var.aws_instance_type
  key_name      = var.key_name
}

So is it necessary or need improve?

Thanks,
James.

**Comment by antonbabenko** [comment]
Hi James,

If `subnet_id` is not specified on `aws_instance` resource, AWS will launch a resource in the default VPC.

The best practice is to be explicit and tell where exactly resources should be launched.

Closing this issue.
