### ISSUE TITLE
Expose lifecycle options

### ISSUE THREAD

**Issue by kclinden** [terraform-aws-modules/terraform-aws-ec2-instance#190]
I have a machine that is provisioned but the AMI is dynamically referenced. I don't want to rebuild the machine when the AMI changes. It would be good to expose the lifecycle options so that I can pass setting changes that should be ignored.

**Comment by bryantbiggs** [comment]
unfortunately that is not something we can control as its an issue in Terraform itself https://github.com/hashicorp/terraform/issues/3116
