### ISSUE TITLE
Add support for metadata_options

### ISSUE THREAD

**Issue by yi2020** [terraform-aws-modules/terraform-aws-ec2-instance#191]
Right now it seems like this module doesn't support the use of metadata_options. This means instances are created with IMDSv1, which has been the basis of hacks in the past. Allowing the use of metadata_options will allow users to use IMDSv2, which is more secure (uses tokens, etc.).

**Comment by yi2020** [comment]
Happy to take on fixing this if that's OK.

**Comment by antonbabenko** [comment]
Yes, PR #193 is in progress :)

**Comment by bryantbiggs** [comment]
closed with #193
