### ISSUE TITLE
adding aws_ebs_volume to instance

### ISSUE THREAD

**Issue by TinajaLabs** [terraform-aws-modules/terraform-aws-ec2-instance#2]
Two of my instance require an ebs volume and I'm trying to get it set up.

I tried using a block in the calling module, but it complains that `should be type list, got map` (see commented section below).

Is it best practice to create an `aws_ebs_volume` and then reference it in the calling module?

Thanks for any tips,
Chris.

```
# create the required volume
resource "aws_ebs_volume" "example1" {
    availability_zone = "us-west-2a"
    size = 40
    tags {
        Name = "HelloWorld"
    }
}

module "ec2_myinstance" {
  source = "terraform-aws-modules/ec2-instance/aws"

  name  = "my-instance"
  count = 5
  
  ami                    = "ami-ebd02392"
  instance_type          = "t2.micro"
  key_name               = "user1"
  monitoring             = true
  vpc_security_group_ids = ["sg-12345678"]

  # <==== set the ebs_block_device
  ebs_block_device = "${aws_ebs_volume.example1.id}"

  # tried this, did not work:
  # ebs_block_device = {
  #   volume_size = 40
  #   volume_type = "gp2"
  #   # delete_on_termination = false
  # }

  tags = {
    Terraform = "true"
    Environment = "dev"
  }
}

```

**Comment by antonbabenko** [comment]
There are several options to use EBS volumes:
1) Create `aws_ebs_volume` resource and attach them to EC2 instances (created using this module) using [aws_volume_attachment](https://www.terraform.io/docs/providers/aws/r/volume_attachment.html) resources.
2) Create both volumes and EC2 instances using this module:
```
ebs_block_device = [ {
   volume_size = 40
   volume_type = "gp2"
} ]
```

Close this issue, if you have no other questions related to this.

**Comment by TinajaLabs** [comment]
I missed the square brackets to create a map type.  Thank you for your patience and help.  Closing.

**Comment by Antony450** [comment]
Hi TinajaLabs,

can you add your code which you used along with map
and also code for adding multiple volumes to a single ec2 instance 
Thanks in advance

**Comment by abhineetraj** [comment]
how do you create one EBS volume for each EC2 instance that spuns up?

I am having problems in attaching the new EBS volume with the EC2 instance. The following code doesn't work.

resource "aws_volume_attachment" "google-prod" {
  device_name                   = "/dev/sdh"
  volume_id                     = "${aws_ebs_volume.google-prod.id}"
  instance_id                   = "${aws_instance.google-prod.id}"
}

Whenever the instance count of aws_instance is increased from 1, the attachment fails
