### ISSUE TITLE
Error launching source instance: InvalidSubnetID.NotFound: The subnet ID 'subnet-ed4ddcb6' does not exist

### ISSUE THREAD

**Issue by mangeshparanjape** [terraform-aws-modules/terraform-aws-ec2-instance#20]
Private Subnet id exist but still getting error. Any idea?
(replaced actual values with xxxxxx)
-----Here is the code to create EC2
module "ec2" {
  source        = "github.com/terraform-aws-modules/terraform-aws-ec2-instance/"
  name          = "${var.instance_name}"
  ami           = "${var.ami}"
  key_name      = "${var.key_name}"
  instance_type = "${var.instance_type}"
  subnet_id = "${var.subnet_id}"
  vpc_security_group_ids = "${concat("${var.default_security_group_list}","${var.security_groups}")}"
  associate_public_ip_address = "${var.associate_public_ip_address}"

  tags = {
    Environment = "${var.environment}"
  }
}

----Here is the output of plan
module.ec2.module.ec2.aws_instance.this: Creating...
  ami:                               "" => "ami-f2d3638a"
  associate_public_ip_address:       "" => "false"
  availability_zone:                 "" => "<computed>"
  disable_api_termination:           "" => "false"
  ebs_optimized:                     "" => "false"
  instance_state:                    "" => "<computed>"
  instance_type:                     "" => "t2.micro"
  ipv6_address_count:                "" => "0"
  key_name:                          "" => "xxxxxx"
  monitoring:                        "" => "false"
  network_interface.#:               "" => "<computed>"
  network_interface_id:              "" => "<computed>"
  placement_group:                   "" => "<computed>"
  primary_network_interface_id:      "" => "<computed>"
  private_dns:                       "" => "<computed>"
  private_ip:                        "" => "<computed>"
  public_dns:                        "" => "<computed>"
  public_ip:                         "" => "<computed>"
  security_groups.#:                 "" => "<computed>"
  source_dest_check:                 "" => "true"
  subnet_id:                         "" => "subnet-xxxxxx"
  tags.%:                            "" => "2"
  tags.Environment:                  "" => "xxxxxxx"
  tags.Name:                         "" => "xxxxxx"
  tenancy:                           "" => "default"
  user_data:                         "" => "xxxxxxxxxxxx"
  volume_tags.%:                     "" => "<computed>"
  vpc_security_group_ids.#:          "" => "1"
  vpc_security_group_ids.1232750057: "" => "sg-xxxxxxx"

---Here is the Error

Error: Error applying plan:

1 error(s) occurred:

* module.ec2.module.ec2.aws_instance.this: 1 error(s) occurred:

* aws_instance.this: Error launching source instance: InvalidSubnetID.NotFound: The subnet ID 'subnet-xxxxxxx' does not exist
        status code: 400, request id: ca4746e1-0660-42ce-84de-84db8ca1769e

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by antonbabenko** [comment]
You can also follow up the same issue described in the AWS Terraform provider - https://github.com/terraform-providers/terraform-provider-aws/issues/3528

**Comment by mangeshparanjape** [comment]
Yes subnet id exist. If i use my custom ec2 module then I don’t see this issue.

**Comment by romulodl** [comment]
Hello, Any update on this issue? I am having a similar problem where clearly the subnet exists but terraform during the `apply` command say it doesn't

**Comment by chuymarin** [comment]
Hello, I was having the same issue just today, in my case terraform was using default access and secret keys, and the ones that I was adding as variables had a wrong variable name, silly issue but almost got me a headache. 

I suggest to run terraform in different regions so you can troubleshoot where is failing, and also describing subnets with aws cli just to confirm that you have correct accesss and secret keys, another thing is that variables precedence can be messing up things, for example if you have env variables setting up the region.

**Comment by antonbabenko** [comment]
I agree with what @chuymarin is saying. Closing this issue as there is not much we can do in regards to the module itself.

Please open a new issue, if you think there is a problem with the module itself.

**Comment by mangeshparanjape** [comment]
Thanks Anton and  Chuymarin. error was misleading which made me look into wrong direction.
I was clearly variable mismatch.

**Comment by nmashfaq** [comment]
> Hello, I was having the same issue just today, in my case terraform was using default access and secret keys, and the ones that I was adding as variables had a wrong variable name, silly issue but almost got me a headache.
> 
> I suggest to run terraform in different regions so you can troubleshoot where is failing, and also describing subnets with aws cli just to confirm that you have correct accesss and secret keys, another thing is that variables precedence can be messing up things, for example if you have env variables setting up the region.

Thanks a ton for this. Initially was trying with an aws `profile` which did not work correctly. Seems to work after making use of `access_key` and `secret_key` attributes.

**Comment by swaroopchirayinkil** [comment]
> Are you sure that you have that subnetid in the correct region? Can you see it in AWS console?

I made the same mistake, mentioned a separate region in the playbook, and used the subnet id of my current region. 

Thank you, boss:+1: )

**Comment by nate-benton90** [comment]
also worth a look at you `AWS_PROFILE` env variable on local (that was my issue). if you want to troubleshoot or verify that, visit [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/caller_identity)

**Comment by tbusot** [comment]
In case it helps someone here: I was unable to create subnets in us-west-2 region. So I had to create in us-east-1, which negated the ami value from the tutorial.
Instead, I used ami-2757f631

provider "aws" {
  profile = "default"
  region  = "us-east-1"
}

resource "aws_instance" "app_server" {
  ami                    = "ami-2757f631"
  instance_type          = "t2.micro"
  vpc_security_group_ids = ["sg-xxx"]
  subnet_id              = "subnet-xxx"

  tags = {
    Name = "ExampleAppServerInstance"
  }
}
