### ISSUE TITLE
How to reference the index of the instance

### ISSUE THREAD

**Issue by franee** [terraform-aws-modules/terraform-aws-ec2-instance#211]
## Description

Hello, I am  trying to specify the specific subnet where the instance will go (to balance them between 2 availability zones).

```
instance_count = 6
subnet_id = module.vpc.public_subnets[count.index % length(module.vpc.public_subnets)]
```

But am getting:
```
Error: Reference to "count" in non-counted context
```

Is there a way to do this at all? Having a variable that holds the current index of the instance to be created?

**Comment by antonbabenko** [comment]
Try this:
```
instance_count = 6
subnet_ids =  module.vpc.public_subnets
```

If you have 2 subnets it will put 6 instances into those subnets automatically (instance number 0, 2, 4 => subnet1; instance number 1, 3, 5 => subnet2).

**Comment by franee** [comment]
@antonbabenko ah cool didn't know it was already baked-in, thank you very much!
