### ISSUE TITLE
Prevent external EBS destroying on instance recreating

### ISSUE THREAD

**Issue by malcolm061990** [terraform-aws-modules/terraform-aws-ec2-instance#214]
## Versions

 - Terraform:
Terraform v0.14.9
 - Provider(s):
provider registry.terraform.io/hashicorp/aws v3.36.0
provider registry.terraform.io/hashicorp/template v2.2.0
 - Module:
 this module

## Reproduction

- create multiple EC2 instances with this module that uses some provisioning script using user_data_base64 with external EBS and attachment:
```
resource "aws_volume_attachment" "clickhouse_cluster" {
  count = 4

  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.clickhouse_cluster[count.index].id
  instance_id = module.clickhouse_cluster.id[count.index]
}

resource "aws_ebs_volume" "clickhouse_cluster" {
  count = 4

  availability_zone = module.clickhouse_cluster.availability_zone[count.index]
  size              = var.ebs_size
}
```

- modify provisioning script and execute `terraform apply`

## Expected behavior
All new instances will attach the volumes that were created before. For example, I created cluster using that module with 4 instances with clickhouse v1 installed. I need to change in provisioning script the clickhouse version from 1 to 2. So, it will install the new version of clickhouse but the previous EBS must be attached to the new instances without destroying those EBS.

## Actual behavior
After changing anything in provisioning script all EBS are destroyed on applying the module with modified script. So I lost all data on NON root partition. In case of clickhouse I lost all database data that was on EBS.

**Comment by malcolm061990** [comment]
Is anybody here?

**Comment by IrmantasMarozas** [comment]
@malcolm061990 Not everyone is able or want to spin up "multiple" EC2 instances and spend their money to "possibly" reproduce the issue.

Have you tried upgrading your module as already suggested by @bryantbiggs ?

**Comment by malcolm061990** [comment]
> 

To reproduce the issue you can spin just two t2.micro machine that are free.
As I have already said the issue is not related to module's version but in 3.2.0 the issue exists.

**Comment by malcolm061990** [comment]
It’s not stale.

**Comment by ivanvarghese** [comment]
This issue seems to be more of a byproduct of coupling both resources into the same lifecycle managed by Terraform and so the modules here reflect that intentional use-case. I have also run into this issue after reusing a few of the published modules.

A potential alternative would be to declare persistent volumes separately and use a data source to import the configuration or script a workflow to check for known volumes, attach or create as necessary, and pass that into instance `user_data` during setup.

**Comment by ttnkumarabhishek** [comment]
@bryantbiggs we are also facing the same issue when we try to create multiple ebs with multiple ec2 instances. 
attached below are the error message which comes after terraform apply.

` # module.c6_mapr_zookeeper[0].aws_instance.this[0] must be replaced
-/+ resource "aws_instance" "this" {
      ~ arn                                  = "some parameter"
      ~ associate_public_ip_address          = false -> (known after apply)
      ~ availability_zone                    = "us-west-2a" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
      - hibernation                          = false -> null
      + host_id                              = (known after apply)
      ~ id                                   =
      ~ instance_initiated_shutdown_behavior = "stop" -> (known after apply)
      ~ instance_state                       = "running" -> (known after apply)
      ~ ipv6_address_count                   = 0 -> (known after apply)
      ~ ipv6_addresses                       = [] -> (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      ~ primary_network_interface_id         = "some parameter"
      ~ private_dns                          = "some parameter"
      ~ private_ip                           = "some parameter"
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      ~ secondary_private_ips                = [] -> (known after apply)
      ~ security_groups                      = [] -> (known after apply)
       
      ~

      - ebs_block_device { # forces replacement
          - delete_on_termination = false -> null
          - device_name           = "/dev/sdf" -> null
          - encrypted             = true -> null
          - iops                  = 3000 -> null
          - kms_key_id            =
          - tags                  = {} -> null
          - throughput            = 125 -> null
          - volume_id             = some parameter" -> null
          - volume_size           = 100 -> null
          - volume_type           = "gp3" -> null
        }
      + ebs_block_device { # forces replacement
          + delete_on_termination = false
          + device_name           = "/dev/sdf"
          + encrypted             = true
          + iops                  = (known after apply)
          + kms_key_id            = "some parameter"
          + snapshot_id           = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 100
          + volume_type           = "gp3"
        }
      + ebs_block_device { # forces replacement
          + delete_on_termination = false
          + device_name           = "/dev/sdg"
          + encrypted             = true
          + iops                  = (known after apply)
          + kms_key_id            = "some parameter"
          + snapshot_id           = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 100
          + volume_type           = "gp3"
        }

      ~ enclave_options {
          ~ enabled = false -> (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }


      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      ~ root_block_device {
          ~ device_name           = "/dev/xvda" -> (known after apply)
          ~ iops                  = 3000 -> (known after apply)
          - tags                  = {} -> null
          ~ throughput            = 125 -> (known after apply)
          ~ volume_id             = "some parameter" -> (known after apply)
            # (5 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

  # module.c6_mapr_zookeeper[1].aws_instance.this[0] must be replaced
-/+ resource "aws_instance" "this" {
      ~ arn                                  = "some parameter" -> (known after apply)
      ~ associate_public_ip_address          = false -> (known after apply)
      ~ availability_zone                    = "us-west-2b" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
      - hibernation                          = false -> null
      + host_id                              = (known after apply)
      ~ id                                   = "some parameter" -> (known after apply)
      ~ instance_initiated_shutdown_behavior = "stop" -> (known after apply)
      ~ instance_state                       = "running" -> (known after apply)
      ~ ipv6_address_count                   = 0 -> (known after apply)
      ~ ipv6_addresses                       = [] -> (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      ~ primary_network_interface_id         = "eni-02936608973006669" -> (known after apply)
      ~ private_dns                          = "some parameter" -> (known after apply)
      ~ private_ip                           = "some parameter" -> (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      ~ secondary_private_ips                = [] -> (known after apply)
      ~ security_groups                      = [] -> (known after apply)
       
        }
      ~ tenancy                              = "default" -> (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
        # (11 unchanged attributes hidden)

      ~ capacity_reservation_specification {
          ~ capacity_reservation_preference = "open" -> (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      ~ credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - ebs_block_device { # forces replacement
          - delete_on_termination = false -> null
          - device_name           = "/dev/sdf" -> null
          - encrypted             = true -> null
          - iops                  = 3000 -> null
          - kms_key_id            = "some parameter -> null
          - tags                  = {} -> null
          - throughput            = 125 -> null
          - volume_id             = "some parameter" -> null
          - volume_size           = 100 -> null
          - volume_type           = "gp3" -> null
        }
      + ebs_block_device { # forces replacement
          + delete_on_termination = false
          + device_name           = "/dev/sdf"
          + encrypted             = true
          + iops                  = (known after apply)
          + kms_key_id            = "some parameter"
          + snapshot_id           = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 100
          + volume_type           = "gp3"
        }
      + ebs_block_device { # forces replacement
          + delete_on_termination = false
          + device_name           = "/dev/sdg"
          + encrypted             = true
          + iops                  = (known after apply)
          + kms_key_id            = "some parameter"
          + snapshot_id           = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 100
          + volume_type           = "gp3"
        }

      ~ enclave_options {
          ~ enabled = false -> (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }


      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      ~ root_block_device {
          ~ device_name           = "/dev/xvda" -> (known after apply)
          ~ iops                  = 3000 -> (known after apply)
          - tags                  = {} -> null
          ~ throughput            = 125 -> (known after apply)
          ~ volume_id             = "some parameter" -> (known after apply)
            # (5 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 2 to add, 0 to change, 2 to destroy.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by
│ the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or
│ when Terraform specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.`. this is the error we are getting every time we try to create multiples ebs blocks.

**Comment by ttnkumarabhishek** [comment]
@bryantbiggs  this is the code block which we are using - 
`##### mapr_zookeeper ######

module "c6_mapr_zookeeper" {
  source                 = "git@github.com:genesismedia/terraform_aws_ec2.git?ref=v1.0.0"
  name                   = join("_", ["c6", local.env_name, "ec2", "uw2", "mapr_zookeeper${count.index + 1}"])
  ami                    = var.mapr_common_ami
  instance_type          = var.mapr_zookeeper_instance_type
  count                  = var.mapr_zookeeper_count
  key_name               = local.env_name
  iam_instance_profile   = aws_iam_instance_profile.ssm_profile.name
  monitoring             = true
  vpc_security_group_ids = [aws_security_group.mapr_zookeeper_sg.id]
  subnet_id              = element(module.vpc.private_subnets, count.index)
  tags                   = merge(local.tags, { schedule = "prod-hours", backup = "true", module = "mapr" })
  root_block_device = [
    {
      volume_type           = "gp3"
      volume_size           = var.mapr_zookeeper_vol_size
      delete_on_termination = false
      encrypted             = true
      kms_key_id            = aws_kms_key.kms_key.arn

    },
  ]
  ebs_block_device = [
    {
      device_name           = "/dev/sdf"
      volume_type           = "gp3"
      volume_size           = var.mapr_zookeeper_extra_vol_size
      encrypted             = true
      kms_key_id            = aws_kms_key.kms_key.arn
      delete_on_termination = false
    },
{
      device_name           = "/dev/sdg"
      volume_type           = "gp3"
      volume_size           = var.mapr_zookeeper_extra_vol_size
      encrypted             = true
      kms_key_id            = aws_kms_key.kms_key.arn
      delete_on_termination = false
    },

  ]


}

`

**Comment by bryantbiggs** [comment]
unfortunately these are not issues related to this module - it appears you are attaching externally created EBS volumes to one or more EC2 instances created by this module and unfortunately we have no control over this lifecycle. You can try filing an issue upstream at the AWS provider but this is a tricky one honestly - you are mixing static and dynamic and that is never a good thing to do

**Comment by ttnkumarabhishek** [comment]
@bryantbiggs Thanks Bryant i will try to keep both the things separate now.
