### ISSUE TITLE
user_data_base64 should fail if it exceeds the max size during plan phase

### ISSUE THREAD

**Issue by geek876** [terraform-aws-modules/terraform-aws-ec2-instance#215]
## Is your request related to a problem? Please describe.
`user_data_base64` size check is only done during `apply` phase. During `plan`, it does'nt look like it is checked and hence the problem only becomes visible when it fails during apply

## Describe the solution you'd like.
Fail `plan` when user_data exceeds the max size allowed

**Comment by antonbabenko** [comment]
Hi,

This is just the way Terraform AWS provider works. We don't change it in the module.
