### ISSUE TITLE
Need to make lifecycle changes a variable

### ISSUE THREAD

**Issue by keepercj** [terraform-aws-modules/terraform-aws-ec2-instance#22]
We cannot use this module without being able to add extra ignore lifecycle change arguments. I.E. user_data, ami, etc.

**Comment by antonbabenko** [comment]
Can you please explain why do you need to ignore changes in arguments like user_data, ami, etc?

**Comment by keepercj** [comment]
AMI is needed as we have weekly images created and shared with our AWS account and a data resource to lookup and grab the new one. User_data is needed because sometimes we have to update options in our cloudinit script and build extra nodes, but this breaks multiple host builds. I.E. We've deployed 5 nodes with 1 version of a cloud init, then want to go back and add 5 more nodes with different options. It accounts for cloudinit config drifts. In any event there should be a way to remove/add lifecycle changes.

**Comment by antonbabenko** [comment]
There is no way to use variables in `lifecycle` block of individual resources and this use-case is not something I think should be in this module.

I recommend you to fork this module and customize for your use case, or consider using [terraform-aws-autoscaling module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/) and adjust `desired capacity` there from 0 to 5.
