### ISSUE TITLE
When using "root_block_device" tags a "ConflictsWith" volume_tags error is generated

### ISSUE THREAD

**Issue by gitbrad** [terraform-aws-modules/terraform-aws-ec2-instance#224]
## Description

When using "root_block_device" tags within an instance created by this module, I encounter the following error even though "volume_tags" are not defined. 

```
Error: ConflictsWith

  on modules/terraform-aws-ec2-instance/main.tf line 89, in resource "aws_instance" "this":
  89:   tags = merge(
  90:     {
  91:       "Name" = var.instance_count > 1 || var.use_num_suffix ? format("%s${var.num_suffix_format}", var.name, count.index + 1) : var.name
  92:     },
  93:     var.tags,
  94:   )

"root_block_device.0.tags": conflicts with volume_tags
```

## Versions
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.39.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

 - Module: 2.19

## Reproduction

 Yes
 Yes
 
With "volume_tags" not defined, using tags in the "root_block_device" section of an instance created by this module creates an error. 

### Code Snippet to Reproduce
```
 root_block_device = [
    {
      volume_type = "gp2"
      volume_size = 250
      tags = {
        snapshotsEnabled = true
      }
    },
  ]
```
With "volume_tags" omitted

## Expected behavior
Terraform is able to cleanly apply the "root_block_device" tags.

## Actual behavior
Cannot apply tags to the "root_block_device" using this module with the above information.

**Comment by argeljoseph** [comment]
You need to set this:
`enable_volume_tags  = false`

**Comment by gitbrad** [comment]
Thanks @argeljoseph that was indeed the fix. Totally missed that!

**Comment by antonbabenko** [comment]
@argeljoseph Thanks for answering this issue!
