### ISSUE TITLE
not able to download module

### ISSUE THREAD

**Issue by abhishekjalanvns** [terraform-aws-modules/terraform-aws-ec2-instance#228]
## Description

when i try to use the module in terraform config and perform terraform init i m getting below error :

Could not download module "ec2_cluster" (main.tf:2) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.18.0": error
│ downloading 'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.18.0': git must be available and on the PATH.
![error](https://user-images.githubusercontent.com/75665644/126608387-9e475eef-63d1-47e3-8849-be68e6199f92.JPG)

CODE USED : 

module "ec2_cluster" {
  source="terraform-aws-modules/ec2-instance/aws"
  version="2.18.0"
  ami="ami-6c1c885c"
  instance_type="t2.micro"
  name="AshuVM"
  subnet_id              = "subnet-eddcdzz4"
}

![code](https://user-images.githubusercontent.com/75665644/126608375-ed00a78f-4f76-4d3c-aa36-173afeb07a40.JPG)

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by argeljoseph** [comment]
Hello, Abishek.. revisit your code espceially the syntax on the source. The [documentation](https://www.terraform.io/docs/language/modules/sources.html) on terraform should help. 🌝
