### ISSUE TITLE
Inputs shown as required on Terraform Registry

### ISSUE THREAD

**Issue by ACannuniRP** [terraform-aws-modules/terraform-aws-ec2-instance#229]
## Description

The following inputs are appearing as required on [Terraform Registry](https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/2.12.0?tab=inputs) but they are not required:

- associate_public_ip_address
- ipv6_address_count
- ipv6_addresses
- private_ip
- user_data
- user_data_base64
- vpc_security_group_ids

**Comment by bryantbiggs** [comment]
a resource definition may not require (optional) certain attributes, but depending on how the module is configured, they may be required. its not a 1:1 between module and the individual resources

**Comment by antonbabenko** [comment]
I guess the issue reported is related to a well-known bug in the Terraform Registry - https://github.com/hashicorp/terraform/issues/21417#issuecomment-765268795
