### ISSUE TITLE
Change "count" variable name to permit future Terraform feature?

### ISSUE THREAD

**Issue by apparentlymart** [terraform-aws-modules/terraform-aws-ec2-instance#23]
Hello!

This module defines a variable called `count`:

https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/7a3aafb6ac20d39d582af9fd41d0270041beb0e7/variables.tf#L5-L8

This is valid in current Terraform, but to implement hashicorp/terraform#953 will require this variable name to be reserved. We're currently hoping to make this name, along with `for_each` and `lifecycle`, reserved names that cannot be used for modules in preparation for them getting special meaning in a later release where that issue is implemented.

Would you be open to changing this variable name to be `instance_count` instead? Although we are not planning to implement `count` for modules immediately, we'd like to begin a deprecation cycle for use of this name as a variable so that the name is free for a change in a later release.

I noticed that `terraform-aws-modules/rds/aws` and `terraform-aws-modules/elb/aws` also have variables called `count`, for which I'd ask a similar question, but I didn't want to spam with loads of issues about the same thing.

Thanks!

**Comment by antonbabenko** [comment]
Martin, thanks for heads up!
