### ISSUE TITLE
Example Ec2 instances are unreachable? 

### ISSUE THREAD

**Issue by filipe-cantarelli** [terraform-aws-modules/terraform-aws-ec2-instance#237]
https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/f939e1fbb59ca2877dcd5a5bcef115f1afc408de/examples/complete/main.tf#L94

Shouldn't the example place all the EC2 instances meant to be public in VPC's module public subnet?

**Comment by antonbabenko** [comment]
There are no requirements for that. EC2 instances can be in public or private.

Answering your question - there can be multiple reasons listed [here](https://aws.amazon.com/premiumsupport/knowledge-center/system-reachability-check/) but they are not related to the module, so I am going to close this issue.
