### ISSUE TITLE
publish an ignore_changes lifecycle

### ISSUE THREAD

**Issue by flypenguin** [terraform-aws-modules/terraform-aws-ec2-instance#239]
## Is your request related to a new offering from AWS?
no

## Is your request related to a problem? Please describe.
for example if i use changing data sources to define properties (e.g. ami images which always point to the "newest" image) a perfectly fine VM would be recreated needlessly. or if an ssh key is being rotated.

the "ignore_changes" lifecycle parameter should cure this.
 

## Describe the solution you'd like.
a new variable "ignore_changes", type list, probably being implemented like this:
```hcm
lifecycle {
  ignore_changes = var.ignore_changes
}
```

## Describe alternatives you've considered.
can't think of some ...

**Comment by antonbabenko** [comment]
Terraform doesn't support variables in `ignore_changes`. We can't do anything about it in the module.

**Comment by flypenguin** [comment]
yeah, JUST found that out myself. thanks for answering!

**Comment by a-schaefers** [comment]
Hey @antonbabenko a lot of us want this ...

Do you think we could open a PR that just duplicates the entire block?

https://stackoverflow.com/a/62432170

**Comment by a-schaefers** [comment]
I know it's not elegant, but it's not our fault since it's a Terraform limitation right now.

But it's less elegant to have ec2 instances stop and start for no reason in production - I'm tasked with figuring this out right now.

Thanks for considering.
