### ISSUE TITLE
Re-output private_ip

### ISSUE THREAD

**Issue by toddmichael** [terraform-aws-modules/terraform-aws-ec2-instance#240]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

I use the `private_ip` output for DNS entries.  I'm unsure how to do this with `private_ip` output removed.

## Describe the solution you'd like.

Re-output `private_ip` or provide a better idea.

## Describe alternatives you've considered.

Use regex function with `private_dns`.

## Additional context

I will often create Route53 entries in public zones to enable IP resolution within or without private network access.

**Comment by antonbabenko** [comment]
Please see this discussion for the explanation and the solution using a data source - https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/pull/234#issuecomment-911490083
