### ISSUE TITLE
Tags are not created when create_spot_instance = true

### ISSUE THREAD

**Issue by prandelicious** [terraform-aws-modules/terraform-aws-ec2-instance#243]
## Description

If `create_spot_instance = true`, tags are not created.

## Versions
 - Terraform: v1.0.8
 - Provider(s): aws v3.62.0

## Reproduction

* Include `create_spot_instance = true` in the module: no tags created
* Remove `create_spot_instance` from the module : tags are created

## Actual behavior
Tags are not created when `create_spot_instances = true`

## Additional context
It appears this issue is with the **AWS** provider and was initially [reported](https://github.com/hashicorp/terraform/issues/3263) back in 2015 but wasn't fixed by Hashicorp.

**Comment by antonbabenko** [comment]
Hi!

As you point out there was an open issue in Terraform AWS provider and we can't do anything about it in the module.
