### ISSUE TITLE
Assign an Elastic IP

### ISSUE THREAD

**Issue by Alexander-Giaquinto** [terraform-aws-modules/terraform-aws-ec2-instance#259]
Hello, would just like to see if there is a possibility to be able to call the aws_eip resource within this module. It seems that it can only be done via the aws_instance resource. Could this be possible?

**Comment by antonbabenko** [comment]
Hi @Alexander-Giaquinto !

You need to create [`aws_eip` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip) outside of this module and assign it to an instance ID returned from the module:
```hcl
module "ec2_instance" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "~> 3.0"

  # ... omitted
}

resource "aws_eip" "this" {
  vpc = true

  instance = module.ec2_instance.id
}
```

It is unlikely that we implement EIP support as a part of this module.
