### ISSUE TITLE
Terraform apply fails when not providing AMI

### ISSUE THREAD

**Issue by matheushr97** [terraform-aws-modules/terraform-aws-ec2-instance#260]
## Description

`terraform apply` fails when the "ami" property is not set. According to the documentation, this property is optional. I was expecting to use the default linux AMI.
```
module "ec2_instance" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "~> 3.0"

  name = "my_ec2"
  ami  = ""  ## default value

  # omit others...
}
```

### Error
```
module.ec2_instance.aws_instance.this[0]: Creating...
╷
│ Error: Error launching source instance: MissingParameter: The request must contain the parameter ImageId
│       status code: 400, request id: 8d52454d-80f1-4056-9d1b-f973b65b013f
│
│   with module.ec2_instance.aws_instance.this[0],
│   on .terraform\modules\ec2_instance\main.tf line 5, in resource "aws_instance" "this":
│    5: resource "aws_instance" "this" {
│
```

## Versions
 - Terraform: Terraform v1.1.0
 - Provider(s): Terraform v1.1.0
 - Module: ec2-instance

**Comment by antonbabenko** [comment]
`ami` is actually required. More info here -  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ami

**Comment by matheushr97** [comment]
> `ami` is actually required. More info here - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ami

I was reading through the terraform-aws-modules documentation. It says the field is optional
https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/latest

**Comment by antonbabenko** [comment]
It is optional if you disable the creation of the module's resources like this:

https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/ab731d112e37971368066b5dbecf35b075a853aa/examples/complete/main.tf#L80-L84
