### ISSUE TITLE
Support for aws_volume_attachment

### ISSUE THREAD

**Issue by tiagomlalves** [terraform-aws-modules/terraform-aws-ec2-instance#276]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: earliest reference was found in version [1.7.0](https://github.com/hashicorp/terraform-provider-aws/blob/release/2.x/CHANGELOG.md#170-january-12-2018)

## Is your request related to a problem? Please describe.
I'm creating an immutable server that stores large volume of data. For that, I create an EC2 instance with ephemeral storage 8Gb, and a permanent storage 100Gb. I would like to define the EC2 instance to use aws_volume_attachment

## Describe the solution you'd like.

When using Terragrunt, I would like to specify the following:

```
terraform {
    source = "tfr:///terraform-aws-modules/ec2-instance/aws//?version=4.0.0"
}

...

dependency "storage" {
    config_path = "PATH_TO_EBS_STORAGE"
}

inputs = {
    ami           = ...
    instance_type = ...

    ebs_volume_attachment = [
        {
            device_name ="/dev/xvdb"
            volume_id = dependency.storage.outputs.id
        }
    ]

    ...
}

...
```

## Describe alternatives you've considered.
Currently I've copied and paste this repo code that defines an `aws_instance` resource to `main.tf` and and `variables.tf` files, with some modifications.

## Additional context
I would be happy to contribute with this change if you think this could help others

**Comment by schniber** [comment]
Hello,

Did you have a look at this ?
=> https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/examples/volume-attachment/main.tf

Hope this helps.

Bests.

**Comment by tiagomlalves** [comment]
@schniber Thanks for the reply. Yes, I had seen that. That example shows how to create an EC2 instance, volume, and `volume_attachment`. My proposal is that the definition of the `volume_attachment` resource could be done by the `ec2` module directly. In Terraform, it's not a big deal to do as in the example. In Terragrunt, however, it would make the code simpler.
