### ISSUE TITLE
Question: What advantages does wrapping the vanilla aws_instance buy you?

### ISSUE THREAD

**Issue by io41** [terraform-aws-modules/terraform-aws-ec2-instance#3]
I'm new to terraform and I've been trying to wrap my head around why you've written this module. From what I can tell, the pros & cons of using your module, instead of the `aws_instance` resource directly are:

### Advantages
- Name tag is generated for you (might be an advantage, it's debatable)

### Disadvantages
- Cannot use `count` in module. (i.e. if I wanted to customise other tags based on `count.index` when using your module, I wouldn't be able to.
- Cannot use `network_interface` parameter
- Cannot specify custom Name tag

This to me seems like a good reason not to use your module... which leaves me trying to understand why you wrote it and published it. I hope you can help me understand. Thanks!

**Comment by antonbabenko** [comment]
I completely understand your frustration, and yes, making module out of single resource seldom makes sense.

In addition to your notes, I want to say that working with "something" (resources - for tiny projects, modules/data-sources - for everything bigger) in the same consistent way across the project is the biggest benefit for me. Also, Terragrunt works with modules and not with resources.

**Comment by io41** [comment]
Hi @antonbabenko, I did not mean to come across frustrated. My apologies. I'm just trying to understand. Consistency has a lot of value... I should have added that to the list of advantages... though forcing consistency at any cost doesn't seem worth it... but I guess terragrunt supplies you with `count` behaviour? I've not had a chance to look at terragrunt yet. Seems like this is the missing piece of the puzzle here. Thanks a mil

**Comment by antonbabenko** [comment]
no, terragrunt doesn't have anything to do with `count`.
