### ISSUE TITLE
Avoid replacement on AMI change

### ISSUE THREAD

**Issue by IgorMilavec** [terraform-aws-modules/terraform-aws-ec2-instance#300]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
When using Windows AMI provided by Amazon, these images are unregistered after 4 months, thereby breaking Terraform configs if we reference specific AMI. If on the other hand we would reference the latest image, that would cause the instances to be replaced.

## Describe the solution you'd like.
I propose to add `ami_replace_on_change` property that would work analogous to `user_data_replace_on_change`. The default value would be `true` to be backwards compatible.
This way we would be able to reference the latest image in our configs.

## Describe alternatives you've considered.
Copying AMI, but it is not permitted.

## Additional context
I can provide a PR if such a solution is accepted.

**Comment by bryantbiggs** [comment]
@IgorMilavec this has to be supported first by the AWS API and then by the AWS provider before we can support it here. Ref https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change
