### ISSUE TITLE
Support credit_specification option for T2.Unlimited instance types

### ISSUE THREAD

**Issue by ricohomewood** [terraform-aws-modules/terraform-aws-ec2-instance#31]
Support for T2.Unlimited was added to the aws_instance resource with block:

credit_specification {
    cpu_credits = "unlimited"
  }

as per https://www.terraform.io/docs/providers/aws/r/instance.html#credit-specification
would be good to add this to your module?

**Comment by antonbabenko** [comment]
[v1.8.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.8.0) has been released. Now you can specify `cpu_credits = "unlimited"` as an argument to the module.
