### ISSUE TITLE
instance auto_recovery option to the EC2 instance

### ISSUE THREAD

**Issue by hiroyasumae** [terraform-aws-modules/terraform-aws-ec2-instance#310]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - This change is supported in [ver 4.12.0](https://registry.terraform.io/providers/hashicorp/aws/4.12.0/docs/resources/instance#auto_recovery) through [latest version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#auto_recovery)

## Is your request related to a problem? Please describe.

AWS EC2 instance has added automatic recovery option function.
Since this value cannot be changed in the current module, I would like to ask you to modify the module so that it can be changed.

## Describe the solution you'd like.

I would like to include the optional input parameter [auto_recovery](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#auto_recovery)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.3.0 :tada:
