### ISSUE TITLE
TAG Lifecycle

### ISSUE THREAD

**Issue by djacquensf9** [terraform-aws-modules/terraform-aws-ec2-instance#311]
Hi all, :) 

I started using the terraform-aws-modules a few weeks, everything is working fine except I have a problem with TAG lifecycle.
Many tags, specially on Root EBS have issue with the lifecycle, everytime I run a terraform apply, they are in turn created or deleted. 
Some Root EBS Name are modified, once with the EBS Name, the following time with the EC2 Name ... 

I thought I should add a lifecycle Meta-Argument in my code but while I manage to do it in ressource, I can not use it with modules.
Is it the right way to solve this issue?

Any feedback are welcomed! ;)

Thanks in advance,

David

**Comment by djacquensf9** [comment]
OK, i discovered this conversation.
https://stackoverflow.com/questions/67778177/terraform-can-i-pass-ignore-changes-to-the-module

I am really troubled now.  
Modules (especially these modules) are great but this is a big drawback if lifecycle can't be implemented easily... 

Thanks

**Comment by antonbabenko** [comment]
Make sure to specify tags on `root_block_device` or `volume_tags` to have them adequately propagated to the resources.

There is nothing we can do in the modules to allow parametrization of `lifecycle` meta-argument because, as you discovered, it is not supported by Terraform.
