### ISSUE TITLE
 source  = "terraform-aws-modules/ec2-instance/aws"

### ISSUE THREAD

**Issue by Iambatmantheknight** [terraform-aws-modules/terraform-aws-ec2-instance#314]
## Description

 source  = "terraform-aws-modules/ec2-instance/aws" 

unable to donwload the GIT file as source does not exist , pls update accordingly

Error: Failed to download module
│
│ Could not download module "ec2-instance" (main.tf:7) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v3.6.0": error 
│ downloading 'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v3.6.0': git must be available and on the PATH.
╵

╷
│ Error: Failed to download module
│
│ Could not download module "ec2-instance" (main.tf:7) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v3.6.0": error 
│ downloading 'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v3.6.0': git must be available and on the PATH.

**Comment by antonbabenko** [comment]
```
module "ec2-instance" {
  source = "terraform-aws-modules/ec2-instance/aws"
  # ...
}
```

More info - https://developer.hashicorp.com/terraform/language/modules/sources

**Comment by Iambatmantheknight** [comment]
module "ec2-instance" {
  source = "terraform-aws-modules/ec2-instance/aws"
  # ...
}
  version = "~>3.0"

Error
terraform init
>>
>>
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/ec2-instance/aws 4.3.0 for ec2-instance...
╷
│ Error: Failed to download module
│
│ Could not download module "ec2-instance" (main.tf:7) source code from
│ "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v4.3.0": error downloading
│ 'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v4.3.0': git must be available and on the
│ PATH.
╵

╷
│ Error: Failed to download module
│
│ Could not download module "ec2-instance" (main.tf:7) source code from
│ "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v4.3.0": error downloading
│ 'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v4.3.0': git must be available and on the
│ PATH.
╵

PS C:\Temp\create a EC2>
