### ISSUE TITLE
Is there way to attach a existent IAM Role to EC2?

### ISSUE THREAD

**Issue by weyderfs** [terraform-aws-modules/terraform-aws-ec2-instance#316]
## Description

I've read and look at code but not found a way to set the attachment of a existent `iam > role + policy` using this module. in my perception always will be create a new.

Is there a way to use a existent?

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by camerondolan** [comment]
Don't know if you still need this - but you can do this using `iam_instance_profile`

So create your role, then create an aws_iam_instance_profile resource. 
Like so:

```
iam policy ect...

resource "aws_iam_role" "ec2_role" {
  role            = "myRole"
  policy_arn = aws_iam_policy.myPolicy.arn
}

resource "aws_iam_instance_profile" "ec2_profile" {
  name = "instanceProfileName"
  role    = aws_iam_role.ec2_role.name
}

```

Then in the ec2 module add the property for `aws_iam_instance_profile` and set it like so:
`iam_instance_profile = aws_iam_instance_profile.ec2_profile.name`

See:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_instance_profile
[iam_instance_profile](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance#input_iam_instance_profile)
