### ISSUE TITLE
feat:Addition of block device information in outputs 

### ISSUE THREAD

**Issue by schniber** [terraform-aws-modules/terraform-aws-ec2-instance#318]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑

## Is your request related to a problem? Please describe.

Ideally the module shout output the block device information that it was able to create.
This is useful specially to retrieve the volume IDs in case we'd like to make use of it (for eg to create Cloudwatch Alarms to monitor the volumes)

## Describe the solution you'd like.

The module should be able to output the block device information (most importantly the volume ids since the other attributes are provided in the inputs)

## Describe alternatives you've considered.

None

**Comment by schniber** [comment]
@bryantbiggs: hello ! is it possible to reopen this issue that got stale ? I provided a fix also and looking forward for a peer review.
Thanks in advance.
Bests

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.4.0 :tada:
