### ISSUE TITLE
Not able to use subnet_ids in ec2 module

### ISSUE THREAD

**Issue by Dhina-test** [terraform-aws-modules/terraform-aws-ec2-instance#328]
Hi , here i am sharing my ec2 module block and error can you help to solve this ?

`module "private_ec2" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "4.2.0"

  name = "private-ec2-ins"

  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  key_name               = var.key_pair
  #monitoring             = true
  vpc_security_group_ids = [module.bastion_sg.security_group_id]
  subnet_ids             = [module.vpc.private_subnets[0], module.vpc.private_subnets[1]]
  user_data =  file("${path.module}/install.sh")

  tags = {
    Terraform   = "true"
    Environment = "dev"
  }
}`

and error in terraform validate
![image](https://user-images.githubusercontent.com/78138014/232681626-027c60be-5004-4172-884c-21398fbaa682.png)

**Comment by antonbabenko** [comment]
Use `subnet_id` as suggested in the error message. [See examples in the readme](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance#single-ec2-instance).

**Comment by Dhina-test** [comment]
Yes @antonbabenko , but i am trying add more than one subnets. and here i am using **subnet_id**  instead of subnet_ids
In may case i defined subnet details in variable section for vpc 

![image](https://user-images.githubusercontent.com/78138014/233285458-2d22f393-381a-4c20-8d1e-74456c575b49.png)


Then i will be calling those in ec2 module from vpc module outputs
![image](https://user-images.githubusercontent.com/78138014/233286279-705b1ddf-b245-4008-b858-09ce2940245c.png)

and now error in terraform validate


![image](https://user-images.githubusercontent.com/78138014/233287136-96c9846f-edde-44f2-b546-b4c6c922a8e7.png)
Can you help for this ?
