### ISSUE TITLE
key_pair does not exists issue

### ISSUE THREAD

**Issue by Dhina-test** [terraform-aws-modules/terraform-aws-ec2-instance#329]
Hi I placed my key pair in currect directoy name as yeshwanth.pem
![image](https://user-images.githubusercontent.com/78138014/233289853-a22aa635-5d91-45b1-bf77-d188341c9015.png)

and for your reference below is my ec2 module terraform code and i defined keypai in veriable section

![image](https://user-images.githubusercontent.com/78138014/233290348-10a80065-f9bb-4fd1-b909-ed1d195d88cf.png)

![image](https://user-images.githubusercontent.com/78138014/233290390-ff68f142-e4f9-4d98-892c-9dbc448d865e.png)

but in terraform validate gots key pair not exist issue

![image](https://user-images.githubusercontent.com/78138014/233290661-76e94721-dc05-4159-8f63-9f6d3bb93527.png)

can you help ?

**Comment by antonbabenko** [comment]
You need to create EC2 key pair in the AWS region you use. You can use [this module](https://github.com/terraform-aws-modules/terraform-aws-key-pair), for example.

Then you will have to specify `key_name` argument pointing to the name of that key pair (not filename) in this ec2-instance module.

Please ask generic Terraform questions on discuss.hashicorp.com
