### ISSUE TITLE
bump versions.tf for module 4.3.1

### ISSUE THREAD

**Issue by silvaalbert** [terraform-aws-modules/terraform-aws-ec2-instance#330]
## Description

Please update `versions.tf` to reflect a requirement for Terraform version 0.15.0 or greater. The new `nonsensitive` function requires that version. Given that this is a breaking change, perhaps it should have been a major release.

https://developer.hashicorp.com/terraform/language/functions/nonsensitive

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 4.3.1

- Terraform version: < 0.15.0

**Comment by dbpyle184** [comment]
Given that this is a possible breaking change for anyone running TF prior to v15.0. Could the update to move to using the nonsentive function be reverted and released in a Major change IE 5.x.x?

**Comment by AdamTylerLynch** [comment]
@antonbabenko this change caused an impact for one of our customers.

**Comment by antonbabenko** [comment]
@bryantbiggs Should we bump `versions.tf` to require Terraform 1.0+ in this module, also?

**Comment by bryantbiggs** [comment]
yes, we can do this in #331 - just want to check a few other things first

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.0.0 :tada:
