### ISSUE TITLE
cpu_core_count and cpu_threads_per_core attributes deprecation in favor of the cpu_options block

### ISSUE THREAD

**Issue by schniber** [terraform-aws-modules/terraform-aws-ec2-instance#332]
## Description

Terraform AWS Provider v4.66 deprecates the use of cpu_core_count and cpu_threads_per_core attributes at the aws_instance level which displays deprecation warnings when running the examples delivered with this module.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v5.0.0

- Terraform version: v1.4.6

- Provider version(s): v4.66.1

## Reproduction Code [Required]

Run the complete example as per this TF module.

## Expected behavior
Terraform plan and apply execute without deprecation warnings.

## Actual behavior

│ Warning: Argument is deprecated
│ 
│   with module.ec2_complete.aws_instance.this[0],
│   on ../../main.tf line 24, in resource "aws_instance" "this":
│   24:   cpu_core_count       = var.cpu_core_count
│ 
│ use 'cpu_options' argument instead
│

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.1.0 :tada:
