### ISSUE TITLE
feat: support for AMD SEV-SNP

### ISSUE THREAD

**Issue by schniber** [terraform-aws-modules/terraform-aws-ec2-instance#333]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: [v4.66.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.66.0)

## Is your request related to a problem? Please describe.
Amazon EC2 now supports AMD Secure Encrypted Virtualization-Secure Nested Paging (AMD SEV-SNP), a feature on AMD EPYC™ processors, on M6a, C6a, and R6a instance types.

## Describe the solution you'd like.
Being able to deploy EC2 Instances running AMD Secure Encrypted Virtualization-Secure Nested Paging (AMD SEV-SNP) through this tf module.

## Describe alternatives you've considered.
None

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.1.0 :tada:
