### ISSUE TITLE
Support private_dns_name_options 

### ISSUE THREAD

**Issue by israel-anaya** [terraform-aws-modules/terraform-aws-ec2-instance#348]
## Description
When creating a new EC2 instance via the web console you have the option to choose the hostname type for the new instance - options are either IP name by default (ip-172-26-0-1.eu-west-3.compute.internal) or Resource name (i-0f0ccc1aa12371b73.eu-west-3.compute.internal). It should be possible to set this option in terraform.
![image](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/assets/40531760/7d21c039-0f05-45ff-a99d-8ff1f834eb21)

## Potential Terraform Configuration
module "ec2_instance" {
  source = "terraform-aws-modules/ec2-instance/aws"
  ...
    private_dns_name_options {
      hostname_type = "resource-name" | "ip-name"
    }
  ...
}

**Comment by manucgm** [comment]
I think this module is missing this config:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance.html#private-dns-name-options

**Comment by dmitry-mightydevops** [comment]
Yes would be nice to support it, right now the plan shows a diff

```hcl
      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }


```
