### ISSUE TITLE
updating associate_public_ip_address should not cause ec2_instance to be replaced

### ISSUE THREAD

**Issue by shichengripple001** [terraform-aws-modules/terraform-aws-ec2-instance#357]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
When I associate_public_ip_address, i got:
module.xxxxx_ec2_instance.module.xxxxx_ec2_instance[1].aws_instance.this[0] must be replaced

## Describe the solution you'd like.
The network interface should be detached, in stead of replacing the instance

**Comment by bryantbiggs** [comment]
this is not due to the module - its due to the API https://github.com/hashicorp/terraform-provider-aws/blob/91e5b0735e748360b790469a77d8dfb7d4943e98/internal/service/ec2/ec2_instance.go#L77
