### ISSUE TITLE
Add support for aditional lifecycle.ignore_changes

### ISSUE THREAD

**Issue by nunofernandes** [terraform-aws-modules/terraform-aws-ec2-instance#36]
Hello,

I'm trying to use your module to create an instance but I wan't to add the user_data to the lyfecycle ignore changes.
It should have an aditional paramenter that could allow that.

**Comment by antonbabenko** [comment]
It is not possible to specify variables in lifecycle block, so you need to fork this module and make changes you want. It won't be supported as a part of this module.
