### ISSUE TITLE
Question: Change size of volumes getting attached when launching EC2 using an AMI that has multiple volumes

### ISSUE THREAD

**Issue by lnkrishnan** [terraform-aws-modules/terraform-aws-ec2-instance#363]
We have a use-case where the AMI prepped by our team has multiple volumes created with varying sizes to satisfy CIS-Compliant Partition sizing requirements.

When spinning up via the EC2 console we get the option to set the volume sizes appropriately as/if required.

Is this possible with terraform and this EC2 module? I tried poking around with creating volumes and attachments based on the example, but as expected, the EC2 service fails saying that there is already a volume at the specified mount point (automatically attached as part of spinning up the EC2 via the module).

**Comment by lnkrishnan** [comment]
@antonbabenko not sure about the rules regarding @-ing folks on here (so pls pardon if I am out of line here), but was wondering if you could take a look at this and comment, when you can? Thanks

**Comment by bryantbiggs** [comment]
this is up to the AWS EC2 API behavior - I would suggest looking at the EC2 docs and specifically its API to see if this behavior is supported

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
