### ISSUE TITLE
override vpc autoassign public_ip_address for created instance

### ISSUE THREAD

**Issue by maciejprzezdziecki** [terraform-aws-modules/terraform-aws-ec2-instance#365]
for now when vpc have that switch enabled and terraform code looks like this:

associate_public_ip_address = false

mentioned setting is ignored

any way to override this behaviour by default ?

**Comment by bryantbiggs** [comment]
I don't follow - this is exposed as a variable https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/6c13542c52e4ed87ca959b2027c85146e8548ac6/main.tf#L43
