### ISSUE TITLE
Add feature to specify custom lifecycle rules

### ISSUE THREAD

**Issue by grommir** [terraform-aws-modules/terraform-aws-ec2-instance#373]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  **Any**

## Describe the solution you'd like.

Add possibility to create more flexible lifecycle rules like `create_before_destroy`, `ignore_changes` etc.

**Comment by antonbabenko** [comment]
There is no way to implement this dynamically in Terraform, so we can't do anything in the modules.
