### ISSUE TITLE
Add public static ip support  for ec2

### ISSUE THREAD

**Issue by jandomanskiit** [terraform-aws-modules/terraform-aws-ec2-instance#377]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Describe the solution you'd like.

Could we add variable type of bool which defining if public EIP will be creating and attaching to ec2 instance?

**Comment by jamallorock** [comment]
it would be useful to add this variable. losing static ip after doing stop and start ec2 is painful...
