### ISSUE TITLE
v5.3.1 does not fix "ami variable when using without ssm" for fresh apply

### ISSUE THREAD

**Issue by ghost** [terraform-aws-modules/terraform-aws-ec2-instance#380]
## Description

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

Release [v5.3.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/tag/v5.3.0) introduced a change to "Remove call data ssm parameter when ami id is specified." This change was then [modified in v5.3.1](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/compare/v5.3.0...v5.3.1) to make this logic more robust through a nested `try(coalesce(...))` statement.

Unfortunately, the current implementation fails on a cold apply (i.e., no existing infrastructure), with `terraform plan` returning the following error: 

```
Error: Invalid count argument

  on .terraform/modules/ec2_server.ec2/main.tf line 10, in data "aws_ssm_parameter" "this":
  10:   count = local.create && var.ami == null ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

## Versions

- Module version [Required]: any version from v5.3.0 onward (up to v5.6.1)

- Terraform version: v1.5.7

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.40.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

1. create a new project
2. create a new EC2 instance with the "terraform-aws-modules/ec2-instance/aws" module
3. include an AMI ID in the `ami` input variable
4. run `terraform init`
5. run `terraform plan` <-- produces error (see above)

## Expected behavior

Prior to v5.3.0, the module works as-expected.

## Actual behavior

Starting with v5.3.0, the module produces an error (see above).

**Comment by imunhatep** [comment]
Same here. 
This module used asterraform code -> module1 -> module2 -> aws-ec2 module.

In case AMI id is determined dynamically in module2, there is no way terraformplan won't fail. And the only workaround seems to define ami id das a string, directly, yet enforcing this approach is an unusable nonsence.

**Comment by vinayakgautamops** [comment]
Same here:

│ Error: Invalid count argument
│
│   on .terraform/modules/vpn_server/main.tf line 12, in data "aws_ssm_parameter" "this":
│   12:   count = local.create && var.ami == null ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only the resources that the count depends on.

**Comment by imunhatep** [comment]
how convenient.. no need to resolve, respond or discuss issues. Simply wait a bit and vuala - no issues 🥇
