### ISSUE TITLE
Add support for network_card_index argument for network interfaces

### ISSUE THREAD

**Issue by erezzarum** [terraform-aws-modules/terraform-aws-ec2-instance#382]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? ✅
It seems to be available since the resource, `aws_instance`, was availabe.
## Is your request related to a problem? Please describe.

Several instances, especially P5 instance, require [specific configuration](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/p5-efa.html) of the network interfaces when attaching to an ec2 instance.
This specific configuration require using a specific `network_card_index` number.
The [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance) terraform resource via the AWS provider does support network_card_index within the [network_interface](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#network-interfaces) block

## Describe the solution you'd like.

Add support for the `network_card_index` within the `dynamic network_interface` block.

Current:
```
  dynamic "network_interface" {
    for_each = var.network_interface

    content {
      device_index          = network_interface.value.device_index
      network_interface_id  = lookup(network_interface.value, "network_interface_id", null)
      delete_on_termination = try(network_interface.value.delete_on_termination, false)
    }
  }
```
After
```
  dynamic "network_interface" {
    for_each = var.network_interface

    content {
      device_index          = network_interface.value.device_index
      network_card_index    = try(network_interface.value.network_card_index, null)
      network_interface_id  = lookup(network_interface.value, "network_interface_id", null)
      delete_on_termination = try(network_interface.value.delete_on_termination, false)
    }
  }
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
