### ISSUE TITLE
Access to metadata service returns 401 unauthorized

### ISSUE THREAD

**Issue by lmilbaum** [terraform-aws-modules/terraform-aws-ec2-instance#387]
## Description

The module source code tracked here - [terraform-test-environment-module](https://github.com/containers/terraform-test-environment-module)

Running the following command from within the instance returns 401 unauthorized
curl http://169.254.169.254/latest/meta-data

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by cgwalters** [comment]
It's likely because [IMDSv2 is enabled](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) in the base image.

Why are you trying to fetch from the metadata service directly versus using cloud-init to execute scripts?

**Comment by lmilbaum** [comment]
> It's likely because [IMDSv2 is enabled](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) in the base image.
> 
> Why are you trying to fetch from the metadata service directly versus using cloud-init to execute scripts?
It is needed for running an external wait command until the user data script run completes
