### ISSUE TITLE
Add support for `metadata_options.http_protocol_ipv6` attribute

### ISSUE THREAD

**Issue by ohmer** [terraform-aws-modules/terraform-aws-ec2-instance#398]
## Is your request related to a new offering from AWS?

Yes ✅

Feature introduced in provider version `5.12.0`:
- https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5120-august-10-2023
- https://github.com/hashicorp/terraform-provider-aws/pull/32759

## Is your request related to a problem?

Not a problem, just a feature that I would like to have.

## Describe the solution you'd like.

Add attribute with default to disabled, add it there:
- https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/main.tf#L298
- https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/variables.tf#L157

## Describe alternatives you've considered.

Using `aws_ec2_instance_metadata_defaults` and forking this module.
Not worth the effort...

## Additional context

I do not know what is the release policy but this would force users to upgrade to provider version `>= 5.12.0`.
I stumbled upon that while working on an IPv6 only experiment. This is niche so a nice to have.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
