### ISSUE TITLE
spot-instances

### ISSUE THREAD

**Issue by johnypony3** [terraform-aws-modules/terraform-aws-ec2-instance#4]
hi everyone, wonderful work with the modules, ive used quite a number of them and they work very well.
i forked this repo to be the base of a spot instance module, the difference is so minuscule that imo it would be better for it to be maintained in this organization/project. my first push is available for viewing here: https://github.com/johnypony3/terraform-aws-ec2-instance
the name of the repo will need to be updated, and maybe some copy.

**Comment by antonbabenko** [comment]
Good work. I wonder if it is possible to merge these two modules by providing default values to parameters you've added which are related to spot instances? If would be great, if it is possible. Do you know?

**Comment by johnypony3** [comment]
i believe all 8 of the variables can be defaulted.
i will know for sure after i test.
what are you thinking?

**Comment by antonbabenko** [comment]
Closing this issue, PR is open.
