### ISSUE TITLE
ec2-instance module is not getting downloaded 

### ISSUE THREAD

**Issue by sheikh221994** [terraform-aws-modules/terraform-aws-ec2-instance#406]
Could not download module "ec2-instance" (module.tf:1) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=29230f956912d751a01a5694510f684754a93196": error
│ downloading 'https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=29230f956912d751a01a5694510f684754a93196': git must be available and on the PATH.

**Comment by sheikh221994** [comment]
I have tried with iam module as well same issue

**Comment by antonbabenko** [comment]
Please check the terraform documentation since this problem is not related to the module but to your local setup.
