### ISSUE TITLE
showing invalid provider configuration and invalid region

### ISSUE THREAD

**Issue by sheikh221994** [terraform-aws-modules/terraform-aws-ec2-instance#407]
Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root
│ module and configure the provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: invalid AWS Region:
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)

**Comment by bryantbiggs** [comment]
this looks like a user configuration error with your provider, not a module issue
