### ISSUE TITLE
How can I put a list in the subnet_id?

### ISSUE THREAD

**Issue by jimethn** [terraform-aws-modules/terraform-aws-ec2-instance#42]
Let's say I have a list of subnets defined in the variable [${module.vpc.private_subnets}]. I want to use this module like so:

```
module "instance" {
    source = "terraform-aws-modules/ec2-instance/aws"
    instance_count = 3
    subnet_id = "${element(module.vpc.private_subnets,count.index)}"
}
```

subnet_id expects a string, not a list, but if I try to use count.index terraform says "count variables are only valid within resources".

**Comment by alexmatsuk** [comment]
This is how I have it done,
subnet_id                   = "${element(module.terraform-aws-vpc.public_subnets,0)}"

**Comment by jimethn** [comment]
Right but that will put all 3 instances into the same subnet. I want to
loop through the subnets based on the count.

**Comment by jimethn** [comment]
Please accept my pull request to add the desired functionality:

https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/pull/43

**Comment by antonbabenko** [comment]
#43 is closed.

The recommended solution is:
```hcl
module "instance_subnet1" {
    source = "terraform-aws-modules/ec2-instance/aws"
    instance_count = 3
    subnet_id = "subnet-123456"
}

module "instance_subnet2" {
    source = "terraform-aws-modules/ec2-instance/aws"
    instance_count = 3
    subnet_id = "subnet-654321"
}
```

**Comment by kunalnanda** [comment]
> Please accept my pull request to add the desired functionality: #43
> 
> It will allow a list to be passed like this:
> 
> ```
> subnet_id = "${join(",", module.vpc.private_subnets)}"
> ```

Just what I was looking for. Thanks.
