### ISSUE TITLE
Can you integrate a provisioner with this module?

### ISSUE THREAD

**Issue by veilig2000** [terraform-aws-modules/terraform-aws-ec2-instance#48]
Is it possible to integrate a provisioner w/ this module?  i.e. chef?   are there any good examples of how to incorporate this?

**Comment by antonbabenko** [comment]
The only way to make use of provisioners right now is to fork this module and add required code there.

If possible, I recommend using [terraform-aws-autoscaling module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/) where you can specify `user_data` and run your provisioners there.

**Comment by speculatrix** [comment]
Hi, I too would enjoy being able to run a provisioner on newly created EC2 instances. I'm not expert enough enough yet to start modifying the model to add it
https://www.terraform.io/docs/provisioners/remote-exec.html

**Comment by antonbabenko** [comment]
There is no way to add provisioner to this reusable module, but it is possible to use `null_resource` which will be using outputs from this module to run any provisioner.

See this for details - https://www.terraform.io/docs/provisioners/null_resource.html

**Comment by ivyleavedtoadflax** [comment]
If anyone else stumbles on this issue wondering the same thing, here is an example of how to integrate a `null_repsonse` resource:

```
resource "null_resource" "my_instance" {

  # Changes to the instance will cause the null_resource to be re-executed
  triggers = {
    instance_ids = module.my_instance.id[0]
  }

  # Running the remote provisioner like this ensures that ssh is up and running
  # before running the local provisioner

  provisioner "remote-exec" {
    inline = ["echo Hello World"]
  }

  connection {
    type        = "ssh"
    user        = "ubuntu"
    private_key = file(var.private_key_path)
    host        = element(module.my_instance.public_ip, 0)
  }

  # Note that the -i flag expects a comma separated list, so the trailing comma is essential!

  provisioner "local-exec" {
    command = "ansible-playbook ../playbooks/docker.yml -u ubuntu -i '${element(module.my_instance.public_ip, 0)},' "
  }
}

```

**Comment by antonbabenko** [comment]
Thanks for sharing, @ivyleavedtoadflax !

I am going to close this issue now.
