### ISSUE TITLE
Unable to launch instance.

### ISSUE THREAD

**Issue by SwathiAbhi** [terraform-aws-modules/terraform-aws-ec2-instance#50]
Error: Error applying plan:

1 error(s) occurred:

* aws_instance.InstancebyTerraform: 1 error(s) occurred:

* aws_instance.InstancebyTerraform: Error launching source instance: MissingInput: No subnets found for the default VPC 'vpc-a14210c9'. Please specify a subnet.
	status code: 400, request id: acf72520-3e0b-40e7-b963-1857e2735efa

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by devsingh0678** [comment]
Looks like there is no default subnet exists in your default VPC.  Create default subnet using AWS CLI, it should work.

**Comment by tonsV2** [comment]
To save others from googling I'll leave the below here

`aws ec2 create-default-subnet --availability-zone ap-southeast-1a`
