### ISSUE TITLE
Existing 'Name' tag in var.tags is overridden

### ISSUE THREAD

**Issue by metmajer** [terraform-aws-modules/terraform-aws-ec2-instance#53]
A tag `Name` is merged into the incoming `var.tags`, independent of whether this key is already contained or not: https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/main.tf#L37.

I assume that by flipping the arguments of the `merge()` function, `var.tags` would get the precedence it needs?

**Comment by antonbabenko** [comment]
You are right, Martin, they have to be swapped. I will make a change now.

**Comment by antonbabenko** [comment]
[v1.14.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.14.0) has this fixed.

Thanks @metmajer for opening this issue and a nudge!
