### ISSUE TITLE
How can use this module to configure each EC2 Instance to use a different AZ

### ISSUE THREAD

**Issue by deveshmehta** [terraform-aws-modules/terraform-aws-ec2-instance#54]
The type of subnet_id is string 

subnet_id | The VPC Subnet ID to launch in | string
-- | -- | --

So how can use this module to configure each EC2 Instance to use a different AZ?

Thanks in advance.
Devesh

**Comment by deveshmehta** [comment]
I manage to solve this by changing the type of subnet_id from string to list (subnet_ids) in variable.tf

variable "subnet_ids" {
  description = "The VPC Subnet ID to launch in"
  type        = "list"
}

Below change in main.tf

subnet_id              = "${element(var.subnet_ids,count.index)}"

It is working as expected :)

**Comment by veilig2000** [comment]
Why don't you put this into a pull request?  Also, how would this work if you are spinning up fewer instances than subnets provided?   ie: two instances but only gave a list of one subnet.

**Comment by craigsands** [comment]
I added the pull request. Terraform uses modular arithmetic with the element function. So if more instances are requested than provided subnet ids, Terraform will just wrap around the list of ids and start from the beginning. See [element-list-index](https://www.terraform.io/docs/configuration/interpolation.html#element-list-index-).

**Comment by antonbabenko** [comment]
Fixed in [v1.15.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.15.0) by @craigsands
