### ISSUE TITLE
volume_tags overwrite aws_ebs_volume tags

### ISSUE THREAD

**Issue by rafstef** [terraform-aws-modules/terraform-aws-ec2-instance#60]
When I create a new aws_volume_attachment to attach an aws_ebs_volume at the instance, the instance  volume_tags overwrite the EBS tags.
On the second apply the aws_ebs_volume tag overwrite the incorrect tag but again on the next operation the instance  volume_tags overwrite the EBS tags.

**Comment by dekimsey** [comment]
Note, this issue is discussed in the upstream [terraform-provider-aws#770](https://github.com/terraform-providers/terraform-provider-aws/issues/770). The work-around is to add `volume_tags` to the list of ignored changes on aws_instances resources.

**Comment by antonbabenko** [comment]
[v1.23.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.23.0) has been released with support for `volume_tags`.

Terraform 0.11 users can use it. Similar functionality for Terraform 0.12 will be released soon.
