### ISSUE TITLE
Error launching source instance: Your requested instance type (t2.micro) not supported in your requested Availability Zone (us-west-2d).

### ISSUE THREAD

**Issue by amitsh728** [terraform-aws-modules/terraform-aws-ec2-instance#68]
Getting this error every now and then while I am running my test configurations. The point to note is, I haven't specified us-west-2d availability zone in any of my configurations. And when I get this error, I do a `terraform destroy` (to destroy created VPC, subnets, etc.), and then run `terraform apply` again. On the second time, it completes without any errors.

**Comment by antonbabenko** [comment]
This kind of errors usually happens when the subnet is not specified (or not specified with the correct value).

Could you verify that you specify correct subnet? Please include terraform code if the problem persists.

**Comment by amitsh728** [comment]
No I am not, but I am creating the complete tire-2 setup from scratch using terraform configuration and only specifying us-west-2 as the region, and amiID. So I couldn't define the subnet ahead of the run. Does that mean such error could not be suppressed in such use-cases?

**Comment by antonbabenko** [comment]
You should reference values from VPC as an argument into this module as specified here - https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/examples/basic/main.tf#L62

**Comment by amitsh728** [comment]
This does seem like a better approach. Thanks.

**Comment by jakemonton** [comment]
Hi, I have the same issue with t2.micro. Other instance type works fine. It only occurs when I create a t2.micro instance. 

I used this https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/examples/basic to create the ec2 instances.

**Comment by antonbabenko** [comment]
@jakemonton AWS may enable and disable certain types of instances or other resources (eg, when AZ is down, you can't launch resources there) at their discretion.

"reference values from VPC as an argument" means that to make this working you need to set `subnet_id` and/or other arguments to valid values.

I hope it helps.

**Comment by jakemonton** [comment]
@antonbabenko I was able to make it work. It was the `subnet_id` value. Thank you!
