### ISSUE TITLE
Not consistent instance naming if initial instance_count is 1 and than count is bumped

### ISSUE THREAD

**Issue by den-is** [terraform-aws-modules/terraform-aws-ec2-instance#69]
Currently if you create ec2 definition with initial `instance_count = 1` it will have no numerical suffix `-1`
https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/c92e80cbd92925da5fb4169c21145470ba906ab2/main.tf#L80
```
my-instance
```
If you later bump that instance count to at least 2 and apply you will get the second instance with `-2` as numerical suffix, while first instance will of course have no suffix
```
my-instance
my-instance-2
```
Of course, if you know you instance count in advance or at least count is > 1 from the very beginning, you will get normal instance names
```
my-instance-1
my-instance-2
...
```

IMHO this is not mathematically consistent and is not aesthetic.

I would like to suggest next possible solution:
> For example, allow optional flag `use_num_suffix`
```hcl
map("Name", (var.instance_count > 1) || (use_num_suffix == "true") ? format("%s-%d", var.name, count.index+1) : var.name)
```

Not all cases can be covered by Auto Scalling group. It's clear that currently provided EC2 naming logic is not consistent.

**Comment by antonbabenko** [comment]
Thanks @den-is for opening this issue.

Please submit a PR with `use_num_suffix` having the default value set to `false` for keeping backward compatibility.
