### ISSUE TITLE
Error: local instance_name: count variables are only valid within resources

### ISSUE THREAD

**Issue by pnduati** [terraform-aws-modules/terraform-aws-ec2-instance#73]
When using the terraform-aws-ec2-instance ec2 module to create an  Ec2 resource we get this error ```Error: local instance_name: count variables are only valid within resources``` even after updating the version to ```version                     = "1.17.0"```
@antonbabenko @den-is

**Comment by den-is** [comment]
@pnduati Thanks.
Before rushing with your PR, you could check PR list and see that there is PR already pending to mitigate that issue https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/pull/72

My fault, I had to test change better :)

**Comment by antonbabenko** [comment]
[v1.18.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.18.0) has been released.
