### ISSUE TITLE
Missing output.instance_public_dns and output.instance_id blocking terraform destroy

### ISSUE THREAD

**Issue by brant4test** [terraform-aws-modules/terraform-aws-ec2-instance#78]
Missing output.instance_public_dns and output.instance_id blocking terraform destroy, any tips? Thanks!

$ terraform destroy
```
Error: Error applying plan:

2 error(s) occurred:

* output.instance_public_dns: At column 24, line 1: list "module.ec2.public_dns" does not have any elements so cannot determine type. in:

${module.ec2.public_dns[0]}
* output.instance_id: At column 16, line 1: list "module.ec2.id" does not have any elements so cannot determine type. in:

${module.ec2.id[0]}
```
Once, even got this error.
```
Error: Error applying plan:

1 error(s) occurred:

* output.instance_id: At column 16, line 1: list "module.ec2.id" does not have any elements so cannot determine type. in:

${module.ec2.id[0]}

```

terraform-aws-ec2-instance v1.19.0 
Terraform v0.11.11

**Comment by antonbabenko** [comment]
Could you share the Terraform code you are running? Also, could you try to run code in `examples` to see it problem is not in your configuration?

**Comment by antonbabenko** [comment]
In Terraform v0.11 you need to reference attribute which can be not existing using `element()`, like this - `${element(module.ec2.id, 0)}`.
