### ISSUE TITLE
Add placement_group to output

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-ec2-instance#8]
Thanks @tehmaspc for reporting this problem in [this comment](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/commit/0f3d09c13d8c8d8d9d49f350b4322bf94c046874#commitcomment-25759405).

When this [related issue](https://github.com/terraform-providers/terraform-provider-aws/issues/2392) is fixed in AWS provider we can add `output` to this module like this:
```hcl
output "placement_group" {
  description = "List of placement groups of instances"
  value       = ["${element(concat(aws_instance.this.*.placement_group, list("")), 0)}"]
}
```

**Comment by antonbabenko** [comment]
Meanwhile, there is a new release [v1.0.4](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/tag/v1.0.4) which works in Terraform 0.11

**Comment by tehmaspc** [comment]
👍 - just tested 1.0.4 on my end and no issues! Cheers!

**Comment by ahmednabhani** [comment]
Tested and no issues! Thanks.

**Comment by antonbabenko** [comment]
[v1.24.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.24.0) has been released with support for placement groups.
