### ISSUE TITLE
not able to boot multizone EC2 instance implementation using terrafrom

### ISSUE THREAD

**Issue by ziamler** [terraform-aws-modules/terraform-aws-ec2-instance#80]
Hi,

I need to boot three ec2 instances in three different aws regions but not able to boot using terrafrom.

Please help me for the same

**Comment by antonbabenko** [comment]
You should call the module multiple times with different providers configurations.

Check this documentation - https://www.terraform.io/docs/configuration/providers.html#selecting-alternate-providers
