### ISSUE TITLE
Unable to provide sunbet_ids

### ISSUE THREAD

**Issue by albertMkhitaryan** [terraform-aws-modules/terraform-aws-ec2-instance#83]
As described in NOTES section : 
One of subnet_id or subnet_ids is required. If both are provided, the value of subnet_id is prepended to the value of subnet_ids. 

I try to use subnet_ids without subnet_id and  get the following error.

Error: module "ec2_cluster": "subnet_ids" is not a valid argument
Error: module "ec2_cluster": missing required argument "subnet_id"

Also I am not able to find any variables called subnet_ids.

**Comment by igor012** [comment]
Hello,
You need to specify the version when calling the module:
```
  source                 = "terraform-aws-modules/ec2-instance/aws"
  version                = "1.15.0"
```

**Comment by kannan-ak** [comment]
Please refer https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/pull/67 
This option is enabled in v1.15.0 (https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.15.0)
